<?php

/**
 * Implements hook_menu
 */
function upload_menu() {
  $items = array();

  $items['upload'] = array(
    'title' => 'Upload Document',
    'description' => 'Upload different type of documents',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('upload_document'),
    'file' => 'upload.inc',
    'access arguments' => array('access content'),
    'type' => MENU_NORMAL_ITEM

  );


  /*****FUTURE*****/
  // The ajax call to calculate the progress bar value
  // $items['upload/progress/%'] = array(
  //   'title' => t('Import progress'),
  //   'page callback' => 'progressbar_progress',
  //   'page arguments' => array(
  //     2,
  //   ),
  //   'access callback' => TRUE,
  //   'type' => MENU_CALLBACK,
  //   'access arguments' => array(
  //     'access content',
  //   ),
  //   'file' => 'upload.inc',
  // );

  return $items;
}

function upload_theme(){
  return array();
}
